### PR TITLE
Added Christmas 2017 meetup to the readme

### PR DESCRIPTION
**Pull request by SuzeShardlow**
Issue #5 refers :)

@angiemaguire @iteles hope this is OK - just practising my GitHub skills again :)

### CODE REVIEW

**Review by iteles — APPROVED** [review]
:tada: LGTM

**Comment by SuzeShardlow** [comment]
@iteles I'm not sure these changes ever got merged in after they were approved :)

**Comment by iteles** [comment]
@SuzeShardlow Same situation as before I'm afraid, these look good to me in terms of the markdown but I don't have any overview of the Glasgow plans, so will leave it to @angiemaguire for the merge 😊

**Comment by angiemaguire** [comment]
@SuzeShardlow Changes now merged. Cheers 😃

**Pull request merged**
